include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint

custom_lint:
  # - missing_provider_scope

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports
    - avoid_print
