name: todo_flutter
description: TODO app built with Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation 2.0
  go_router: ^6.2.0

  # State management
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0

  # Generate code
  freezed_annotation: ^2.2.0

  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_analytics: ^10.1.4
  firebase_crashlytics: ^3.0.15
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_ui_firestore: ^1.2.9

  # Authentication
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0

  # Util
  window_manager: ^0.3.1
  uuid: ^3.0.7

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flex_color_scheme: ^6.1.2
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1
  custom_lint: ^0.2.12
  riverpod_lint: ^1.1.2

  # Generate code
  build_runner: ^2.3.3
  riverpod_generator: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
