name: todo_flutter
description: TODO app built with Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation 2.0
  go_router: ^6.5.7

  # State management
  flutter_riverpod: ^2.3.5
  riverpod_annotation: ^2.1.0

  # Generate code
  freezed_annotation: ^2.2.0

  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.1.1
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  firebase_ui_firestore: ^1.3.2
  firebase_app_check: ^0.1.2+2

  # Authentication
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0

  # Util
  window_manager: ^0.3.2
  uuid: ^3.0.7

  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flex_color_scheme: ^7.0.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.1
  custom_lint: ^0.3.3
  riverpod_lint: ^1.3.0

  # Generate code
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
